# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: "/img/logo_miccall.png"
  keywords: Transvision
  backgroundpic: "img/bg.jpg"

Intro:
  name: Transvision
  slogan: "Translate but never late"
  HeadButton: 大译象

Nav:
  Home_name: 译象主页
  is_use_categories: false
  # categories_name: 分类
  is_use_archives: false
  # archives_name: 归档

  #Social
  # for more icons, please see http://fontawesome.io/icons/#brand
  icon:
    # github: https://github.com/miccall
    # 500px: http://500px.com
    #        wechat:
    weibo: https://weibo.com
    home: http://www.transvisioner.com

  pages:
    # 自定义连接页
    # 译象主页，译象简介、译象服务、译象案例、译象客户、译象风采、加入译象、联系译象
    # link 的参数为相对路径，对应 hexo 目录下的 source 件夹内的相应文件夹
    译象服务:
      link: "/price/"
    译象案例:
      link: "/case/"
    译象客户:
      link: "/customer/"
    译象风采:
      link: "/group/"
    译象简介:
      link: "/about/"
    加入译象:
      link: "/join/"
    联系译象:
      link: "/contact/"

MainFirst:
  name: Transvision
  description: "大译象,大异象 <br> Translation, Transvision"
  pic_url: "/img/background/me.jpg"
  goto_ulr: ""

Gallery:
  title: Mr.metro
  description: 翻译案例

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染
# default dark funky okaidia twilight coy solarized  可选项
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
  use:
  shortname: http-miccall-tech
  duoshuo_thread_key_type: path
  duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
  changyan_appid:
  changyan_conf:
  changyan_thread_key_type: path
  # 使用 valine 请先执行 npm install valine --save
  valine: # Valine Comment System https://github.com/xCss/Valine
    on: true
    appId: 'your appId'
    appKey: 'your appkey'
    notify: true
    verify: false
    placeholder: Please leave your footprints
    avatar: ''
    avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
    pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
  use: google
  swiftype_key: Just another fine responsive


# Leancloud Views
leancloud:
  enable: false
  app_id: #你的 app_id
  app_key: #你的 app_key
  av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
  enable: false
  all_site_uv: true
  post_pv: true
  busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
